resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: redis_pr
    type: pull-request
    check_every: 3m
    source:
      repository: eloqdata/eloqkv
      base_branch: "main"
      access_token: ((git-token))
      ignore_drafts: true
      disable_forks: false
      labels: ["trigger-ci"]

  - name: logservice_src
    type: git
    check_every: 3m
    source:
      branch: main
      uri: git@github.com:eloqdata/eloq_log_service.git
      private_key: ((git-key))

  - name: eloq_test_src
    type: git
    check_every: 3m
    source:
      branch: main
      uri: git@github.com:eloqdata/eloq-test.git
      private_key: ((git-key))

  - name: raft_host_manager_src
    type: git
    check_every: 3m
    source:
      branch: main
      uri: git@github.com:eloqdata/raft_host_manager.git
      private_key: ((git-key))

  - name: eloq_ubuntu_2404
    type: registry-image
    source:
      repository: eloqdata/monograph-dev-ci-ubuntu2404
      tag: latest

jobs:
  - name: compile-test
    build_log_retention:
      builds: 500
    serial: true
    plan:
      - in_parallel:
          steps:
            - get: redis_pr
              trigger: true
              version: every
            - get: logservice_src
            - get: raft_host_manager_src
            - get: eloq_test_src
            - get: eloq_ubuntu_2404
      - put: redis_pr
        params:
          path: redis_pr
          status: pending
      - task: compile-test-task
        image: eloq_ubuntu_2404
        file: redis_pr/concourse/tasks/pr.ent.yml
        vars:
          cass-host: ((cassandra-host))
          minio-access-key: ((minio-access-key))
          minio-endpoint: ((minio-endpoint))
          minio-secret-key: ((minio-secret-key))
          git-ssh-key: ((git-key))
        privileged: true
        on_failure:
          put: redis_pr
          params:
            path: redis_pr
            status: failure
      - put: redis_pr
        params:
          path: redis_pr
          status: success
